name: cloudflare_dyn_dns
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  args: ^2.5.0
  collection: ^1.19.0
  http: ^1.2.1
  xdg_directories: ^1.0.4
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0

executables:
  cloudflare_dyn_dns: main
